In [ ]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=6b0ec39db02253889c94efb7eaba2de379fb720b2ff6f98bb913baba8b9ae782
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
import pandas as pd

df = pd.read_excel("Dataset for Data Analytics (1).xlsx")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [ ]:
pysqldf("SELECT * FROM df LIMIT 5")

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00.000000,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00.000000,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00.000000,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00.000000,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00.000000,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
pysqldf("""
SELECT Product, COUNT(*) as count
FROM df
GROUP BY Product
""")

   Product  count
0    Chair    178
1     Desk    170
2   Laptop    173
3  Monitor    163
4    Phone    156
5  Printer    181
6   Tablet    179

In [ ]:
pysqldf("""
SELECT Product, SUM(TotalPrice) as revenue
FROM df
GROUP BY Product
ORDER BY revenue DESC
""")

   Product    revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

In [ ]:
pysqldf("""
SELECT PaymentMethod, COUNT(*) as total
FROM df
GROUP BY PaymentMethod
""")

  PaymentMethod  total
0          Cash    246
1   Credit Card    234
2    Debit Card    232
3     Gift Card    230
4        Online    258

In [ ]:
pysqldf("""
SELECT OrderStatus, COUNT(*) as total
FROM df
GROUP BY OrderStatus
""")

  OrderStatus  total
0   Cancelled    250
1   Delivered    231
2     Pending    237
3    Returned    247
4     Shipped    235

In [ ]:
pysqldf("""
SELECT * FROM df
WHERE Product = 'Laptop'
""")

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200006,2025-06-17 00:00:00.000000,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
1,ORD200013,2023-08-30 00:00:00.000000,C88348,Laptop,3,201.49,903 Main St,Credit Card,Returned,TRK81913874,4,FREESHIP,Facebook,604.47
2,ORD200024,2024-10-30 00:00:00.000000,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
3,ORD200026,2024-03-06 00:00:00.000000,C21944,Laptop,5,59.55,296 Main St,Online,Delivered,TRK80276812,6,None,Referral,297.75
4,ORD200036,2025-05-08 00:00:00.000000,C59337,Laptop,2,534.43,465 Main St,Debit Card,Pending,TRK50961250,5,None,Facebook,1068.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,ORD201156,2023-07-19 00:00:00.000000,C20512,Laptop,4,690.78,980 Main St,Credit Card,Shipped,TRK98234737,9,None,Referral,2763.12
169,ORD201163,2024-06-11 00:00:00.000000,C30643,Laptop,3,306.29,966 Main St,Credit Card,Returned,TRK19477485,7,WINTER15,Instagram,918.87
170,ORD201168,2023-04-08 00:00:00.000000,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
171,ORD201179,2023-01-08 00:00:00.000000,C84630,Laptop,5,518.55,907 Main St,Credit Card,Cancelled,TRK48054997,6,WINTER15,Instagram,2592.75
172,ORD201184,2023-09-27 00:00:00.000000,C10222,Laptop,1,204.08,979 Main St,Gift Card,Returned,TRK86297895,4,None,Google,204.08